FROM node:9.11.2-stretch
LABEL numigi <contact@numigi.com>

RUN useradd -ms /bin/bash client
WORKDIR /home/client

USER client

COPY .docker_files/package.json .docker_files/package-lock.json ./
RUN npm install

COPY .docker_files/ava ava
# COPY vue_stock_forecast vue_stock_forecast
